/** Ключи стадий — подписи в `src/locales/site.js` → `site.stages` */
export const STAGE_KEY = {
    construction: 'construction',
    standard_design: 'standard_design',
    completed: 'completed',
    pending_build: 'pending_build',
    concept: 'concept',
}

export const TYPE_PROJECT = {
    house: 'house',
    interior: 'interior',
}

export const projectPreviews = [
    {
        id: 1,
        year: '2024',
        name: 'КП РЕПИНО ПАРК',
        pathUrl: 'kp-repino-park-1',
        stageKey: STAGE_KEY.construction,
        square: '480 м2',
        image: 'https://firebasestorage.googleapis.com/v0/b/nearwater-c02a9.appspot.com/o/pereDesign%2Flist%2FpereProject_1.png?alt=media&token=5c87dc54-c8bc-4d82-980f-14910a7bd25e',
        type: TYPE_PROJECT.house,
    },
    {
        id: 2,
        year: '2024',
        name: 'КП РЕПИНО ПАРК',
        pathUrl: 'kp-repino-park-2',
        stageKey: STAGE_KEY.construction,
        square: '250 м2',
        image: 'https://firebasestorage.googleapis.com/v0/b/nearwater-c02a9.appspot.com/o/pereDesign%2Flist%2FpereProject_2.png?alt=media&token=fa68d9b2-e112-4602-a5bb-10af05405c97',
        type: TYPE_PROJECT.house,
    },
    {
        id: 3,
        year: '2023',
        name: 'PERE_DESIGN_H3',
        pathUrl: 'pere-design-h3',
        stageKey: STAGE_KEY.standard_design,
        square: '160 м2',
        image: 'https://firebasestorage.googleapis.com/v0/b/nearwater-c02a9.appspot.com/o/pereDesign%2Flist%2FpereProject_3.jpg?alt=media&token=57a892dd-3fc1-4968-9333-af262eac02ef',
        type: TYPE_PROJECT.house,
    },
    {
        id: 4,
        year: '2023',
        name: 'ОРЕХОВО',
        pathUrl: 'orekhovo',
        stageKey: STAGE_KEY.completed,
        square: '160 м2',
        image: 'https://firebasestorage.googleapis.com/v0/b/nearwater-c02a9.appspot.com/o/pereDesign%2Flist%2FpereProject_4.png?alt=media&token=9b0125e9-808e-43ea-85dd-c649d9753203',
        type: TYPE_PROJECT.house,
    },
    {
        id: 5,
        year: '2024',
        name: 'КП ПЕТЕРГОФСКИЕ ДАЧИ',
        pathUrl: 'kp-petergofskie-dachi',
        stageKey: STAGE_KEY.pending_build,
        square: '160 м2',
        image: 'https://firebasestorage.googleapis.com/v0/b/nearwater-c02a9.appspot.com/o/pereDesign%2Flist%2FpereProject_5.png?alt=media&token=31bacf60-f9c2-4622-af01-811e50d232fb',
        type: TYPE_PROJECT.house,
    },
    {
        id: 6,
        year: '2022',
        name: 'КП ЗЕЛЕНЫЙ ОСТРОВ',
        pathUrl: 'kp-zelenyj-ostrov',
        stageKey: STAGE_KEY.completed,
        square: '160 м2',
        image: 'https://firebasestorage.googleapis.com/v0/b/nearwater-c02a9.appspot.com/o/pereDesign%2Flist%2FpereProject_6.png?alt=media&token=66e13a86-9872-4b36-9f51-ebf03bb2199d',
        type: TYPE_PROJECT.house,
    },
    {
        id: 7,
        year: '2023',
        name: 'НИЗИНО',
        pathUrl: 'NIZINO-1',
        stageKey: STAGE_KEY.completed,
        square: '230 м2',
        image: 'https://firebasestorage.googleapis.com/v0/b/nearwater-c02a9.appspot.com/o/pereDesign%2Flist%2FpereProject_7.png?alt=media&token=3ec5d1f2-15e4-4749-afe6-3b581c8a39a6',
        type: TYPE_PROJECT.house,
    },
    {
        id: 8,
        year: '2021',
        name: 'ПАРГОЛОВО',
        pathUrl: 'PARGOLOVO',
        stageKey: STAGE_KEY.pending_build,
        square: '240 м2',
        image: 'https://firebasestorage.googleapis.com/v0/b/nearwater-c02a9.appspot.com/o/pereDesign%2Flist%2FpereProject_9.png?alt=media&token=5b4829c7-e845-456a-9bc4-62a4f094551c',
        type: TYPE_PROJECT.house,
    },
    {
        id: 9,
        year: '2023',
        name: 'НИЗИНО',
        pathUrl: 'NIZINO-2',
        stageKey: STAGE_KEY.construction,
        square: '250 м2',
        image: 'https://firebasestorage.googleapis.com/v0/b/nearwater-c02a9.appspot.com/o/pereDesign%2Flist%2FpereProject_8.jpg?alt=media&token=b4f29450-98b5-4a8e-b7cd-ac88e5470427',
        type: TYPE_PROJECT.house,
    },
    {
        id: 10,
        year: '2022',
        name: 'ИСТРА',
        pathUrl: 'ISTRA',
        stageKey: STAGE_KEY.pending_build,
        square: '270 м2',
        image: 'https://firebasestorage.googleapis.com/v0/b/nearwater-c02a9.appspot.com/o/pereDesign%2Flist%2FpereProject_10.png?alt=media&token=2078fd26-c3dc-4df5-a18e-445df47fdbda',
        type: TYPE_PROJECT.house,
    },
    {
        id: 11,
        year: '2023',
        name: 'ИЖЕСВК',
        pathUrl: 'IZHESVK',
        stageKey: STAGE_KEY.construction,
        square: '210 м2',
        image: 'https://firebasestorage.googleapis.com/v0/b/nearwater-c02a9.appspot.com/o/pereDesign%2Flist%2FpereProject_11.png?alt=media&token=a028c81b-8b7c-451c-b577-bc8189508735',
        type: TYPE_PROJECT.house,
    },
    {
        id: 12,
        year: '2022',
        name: 'КОРКИНСКИЕ ХОЛМЫ',
        pathUrl: 'KORKINSKIE-CHOLMI',
        stageKey: STAGE_KEY.completed,
        square: '140 м2',
        image: 'https://firebasestorage.googleapis.com/v0/b/nearwater-c02a9.appspot.com/o/pereDesign%2Flist%2FpereProject_12.png?alt=media&token=214a4a55-51aa-466a-ab06-baba89da192e',
        type: TYPE_PROJECT.house,
    },
    {
        id: 13,
        year: '2024',
        name: 'СЕРПУХОВ',
        pathUrl: 'SERPUKHOV',
        stageKey: STAGE_KEY.construction,
        square: '160 м2',
        image: 'https://firebasestorage.googleapis.com/v0/b/nearwater-c02a9.appspot.com/o/pereDesign%2Flist%2FpereProject_13.png?alt=media&token=66dc5162-7a04-4906-a543-7dedb9406ce0',
        type: TYPE_PROJECT.house,
    },
    {
        id: 14,
        year: '2022',
        name: 'ЦВЕТКОВО',
        pathUrl: 'CVETKOVO',
        stageKey: STAGE_KEY.completed,
        square: '190 м2',
        image: 'https://firebasestorage.googleapis.com/v0/b/nearwater-c02a9.appspot.com/o/pereDesign%2Flist%2FpereProject_14.png?alt=media&token=269dfe20-014a-4ab9-a5fd-94dcbf6991a6',
        type: TYPE_PROJECT.house,
    },
    {
        id: 15,
        year: '2023',
        name: 'НАРА',
        pathUrl: 'NARA',
        stageKey: STAGE_KEY.construction,
        square: '270 м2',
        image: 'https://firebasestorage.googleapis.com/v0/b/nearwater-c02a9.appspot.com/o/pereDesign%2Flist%2FpereProject_15.png?alt=media&token=8dab2da6-36f2-442b-aac2-3117b15678eb',
        type: TYPE_PROJECT.house,
    },
    {
        id: 16,
        year: '2024',
        name: 'КП ВИТЯЗЬ',
        pathUrl: 'KP-VITYAZ',
        stageKey: STAGE_KEY.construction,
        square: '680 м2',
        image: 'https://firebasestorage.googleapis.com/v0/b/nearwater-c02a9.appspot.com/o/pereDesign%2Flist%2FpereProject_16.png?alt=media&token=9377a1c8-f069-4ca5-b49f-275caf83f456',
        type: TYPE_PROJECT.house,
    },
    {
        id: 17,
        year: '2024',
        name: 'СЕРГИЕВ ПОСАД',
        pathUrl: 'SERGIEV-POSAD',
        stageKey: STAGE_KEY.pending_build,
        square: '330 м2',
        image: 'https://firebasestorage.googleapis.com/v0/b/nearwater-c02a9.appspot.com/o/pereDesign%2Flist%2FpereProject_17.png?alt=media&token=fa1b9f1b-fb76-4e93-b0d8-ac0951cbd191',
        type: TYPE_PROJECT.house,
    },
    {
        id: 18,
        year: '2023',
        name: 'ВИЛЛА СТОУН',
        pathUrl: 'VILLA-STOUN',
        stageKey: STAGE_KEY.concept,
        square: '190 м2',
        image: 'https://firebasestorage.googleapis.com/v0/b/nearwater-c02a9.appspot.com/o/pereDesign%2Flist%2FpereProject_18.png?alt=media&token=7d577126-7168-40bf-a919-7e8056f5ba71',
        type: TYPE_PROJECT.interior,
    },
    {
        id: 19,
        year: '2023',
        name: 'НИЗИНО',
        pathUrl: 'NIZINO-3',
        stageKey: STAGE_KEY.construction,
        square: '240 м2',
        image: 'https://firebasestorage.googleapis.com/v0/b/nearwater-c02a9.appspot.com/o/pereDesign%2Flist%2FpereProject_19.png?alt=media&token=c1c76dda-d21b-4b15-8eb1-c740d40b62ca',
        type: TYPE_PROJECT.interior,
    },
    {
        id: 20,
        year: '2025',
        name: 'КП ЮККОВСКОЕ',
        pathUrl: 'KP-YUKKOVSKOE',
        stageKey: STAGE_KEY.construction,
        square: '150 м2',
        image: 'https://firebasestorage.googleapis.com/v0/b/nearwater-c02a9.appspot.com/o/pereDesign%2Flist%2FpereProject_20.png?alt=media&token=db3b659f-7342-454a-aa8c-2d0fe566cf8b',
        type: TYPE_PROJECT.interior,
    },
]
